VisualStudio 2015 compilation fix
The compilation error is

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xutility(2316): error C2280: 'OSL_v1_9::OSLQuery::Parameter &OSL_v1_9::OSLQuery::Parameter::operator =(const OSL_v1_9::OSLQuery::Parameter &)': attempting to reference a deleted function
D:\dev\Thirdparty\OSL-1.9\src\include\OSL/oslquery.h(82): note: compiler has generated 'OSL_v1_9::OSLQuery::Parameter::operator =' here

The reason is because there is an explicit move constructor for
Parameter now, meaning an implicit assignment operator is deleted. See http://en.cppreference.com/w/cpp/language/copy_assignment