VisualStudio 2015 x64 compilation fixes for 1.9.x (#820)
* VisualStudio 2015 x64 build fix

include/OSL/dual.h(64): error C2476: 'constexpr' constructor does not
initialize all members

According to http://en.cppreference.com/w/cpp/language/constexpr, this
is an expected error for C++11, but not for C++14 and beyond.

* VisualStudio 2015 x64 build fix

Using SimplePool in the member variables in ShadingContext is causing an
'attempting to reference a deleted function' error for the
std::unique_ptr<char>s.

Applying the rule of 5, to disallow copying or moving a SimplePool.